name: walmart_project 
version: "1.0.0" 
config-version: 2 
profile: walmart_profile 
  
model-paths: ["models"] 
snapshot-paths: ["snapshots"] 
macro-paths: ["macros"]
test-paths: ["tests"]
  
models: 
  walmart_project: 
    staging: 
      +schema: SILVER 
      +materialized: view 
    marts: 
      +schema: GOLD 
      +materialized: table 

snapshots:
    walmart_project:
        +target_schema: GOLD